### ISSUE TITLE
W2: initialiseFields

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#16]

**Comment by irvcaza** [comment]
I have a strange problem when I run the code, it shows 
`*** stack smashing detected ***: ./lbsim terminated
Aborted (core dumped)`
And and you can solve it if you comment the line 29 in `readParameters`
`read_double(szFileName, "characteristicvelocity_y", &velocityWall[1]);`

Now is solved, `velocityWall` was defined as double, not array
You don't need to worry about it
