### ISSUE TITLE
W2: treatBoundary

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#19]

**Comment by irvcaza** [comment]
Pre written code
`
#include "boundary.h"

int DotProd (int V1, int V2){
    int i, d = 0;
    for (i=0;i<3;i++)
        d+= V1[i]*V2[i];
    return d;
}

void NoSlipCell(double _collideField, int length_tot, int x, int y, int z, int_ V_norm){
    int i, coord_dest[3];  
    for (i=0;i<19;i++){
        coord_dest[0] = x + LATTICEVELOCITIES[i][0];
        coord_dest[1] = x + LATTICEVELOCITIES[i][1];
        coord_dest[2] = x + LATTICEVELOCITIES[i][2];
        if (coord_dest[0] >0 && coord_dest[0] <length_tot &&  coord_dest[1] >0 && coord_dest[1] <length_tot && coord_dest[3] >0 && coord_dest[3] <length_tot){
            *getEl(collideField, x, y, z, i, length_tot) = *getEl(collideField, coord_dest[0], coord_dest[1], coord_dest[2], 18-i, length_tot);
        }
    }
}

void MovingCell(double _collideField, const double \* const wallVelocity, int length_tot, int x, int y, int z, int_ V_norm){
    int i,j, coord_dest[3]; 
    for (i=0;i<19;i++){
        coord_dest[0] = x + LATTICEVELOCITIES[i][0];
        coord_dest[1] = x + LATTICEVELOCITIES[i][1];
        coord_dest[2] = x + LATTICEVELOCITIES[i][2];
        if (coord_dest[0] >0 && coord_dest[0] <length_tot &&  coord_dest[1] >0 && coord_dest[1] <length_tot && coord_dest[3] >0 && coord_dest[3] <length_tot){

```
        *getEl(collideField, x, y, z, i, length_tot) = *getEl(collideField, coord_dest[0], coord_dest[1], coord_dest[2], 18-i, length_tot);
    }
}
```

}

void treatBoundary(double _collideField, int_ flagField, const double \* const wallVelocity, int xlength){
    iint x, y, z, length_tot=xlength +2;

```
z = 0;
for (y = 0; y <= xlength+1; ++y){
    for (x = 0; x <= xlength+1; ++x){           
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 1);
    }
}
for (z = 1; z <= xlength; ++z){
    y = 0;
    for (x = 0; x <= xlength +1; ++x){
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 1);
    }       
    for (y = 1; y <= xlength; ++y){
        x = 0;
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 1);
        for (x = 1; x <= xlength; ++x){             
            initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 0);
        }
        x = xlength+1;
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 1);
    }
    y = xlength+1;
    for (x = 0; x <= xlength+1; ++x){
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 1);
    }
}
z = xlength+1;
for (y = 0; y <= xlength+1; ++y){
    for (x = 0; x <= xlength+1; ++x){
        initialiseCell(collideField, streamField, flagField, length_tot, x, y, z, 2);
    }
}
```

}
`
