### ISSUE TITLE
Project: add gravity term to collide step

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#39]
- [x] change collide step
- [x] build example with cavity, we should see some pressure gradient from top to bottom

**Comment by nasay** [comment]
In Master thesis it is formula (4.5). Probably further be found can be found in an Origin paper (KPR+04).

**Comment by irvcaza** [comment]
Done in [here](https://github.com/nathanwbrei/cfdlab/commit/753ac826abb7bea1c2db76a436bc08d272933d2c)
