### ISSUE TITLE
Project: Add test functions for cell values

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#42]
- [ ] for mass
- [ ] for velocity ?

**Comment by irvcaza** [comment]
What do you mean by test functions ?

**Comment by nasay** [comment]
I mean just add some security checks probably in collide step, if velocity is greater then speed of sound, density of fluid is smaller then ... 0.9 or bigger 1.1. And if such thing happened, then throw an error. It will save us a lot of time of setting up paraview with wrong results.
If you know what else we can check - comment:).

**Comment by irvcaza** [comment]
Ah ok, also check if the flags of liquid and gas are adjacent (without interface). Also a function that gathers and  outputs the total mass
Those are my ideas.
I can do that

**Comment by nasay** [comment]
Great! I will push massField until tomorrow.

**Comment by nasay** [comment]
I changed `norm(velocity) < C_S * C_S` to `norm(velocity) < 3 * C_S * C_S`, since `C_S` is a value along one dimention.
