### ISSUE TITLE
Add MPI support

### ISSUE THREAD

**Issue by nasay** [nathanwbrei/cfdlab#53]
we also need to communicate mass and maybe fluid fraction fields.

**Comment by irvcaza** [comment]
But but but why? Do you want it to run in parallel? Why not use OMP?

**Comment by nasay** [comment]
I thought it would be easier to update our existing code for MPI...

**Comment by irvcaza** [comment]
Ok we can make it as extra (for extra points)

**Comment by nasay** [comment]
OpenMP was added
